select FIRST_NAME ,NUMBER_OF_GUESTS 
from Guest , BOOKING 
where BOOKING.CUSTOMER_ID = Guest.CUSTOMER_ID ;
--2
select Rates ,RESERVATION_NUMBER 
from ROOM , BOOKING 
where BOOKING.ROOM_NUMBER = ROOM.ROOM_NUMBER ;
--3
select PHONE_NUMBER ,END_DATETIME 
from Guest , BOOKING 
where BOOKING.CUSTOMER_ID = Guest.CUSTOMER_ID ;
--4
select START_DATETIME ,ROOM_TYPE 
from ROOM , BOOKING 
where BOOKING.CUSTOMER_ID = ROOM.CUSTOMER_ID ;
--5
select ROOM_LOCATION ,RESERVATION_NUMBER 
from ROOM , BOOKING 
where BOOKING.ROOM_NUMBER = ROOM.ROOM_NUMBER ;

